### ISSUE TITLE
ErrorException in Headers.php line 83

### ISSUE THREAD

**Issue by itecassist** [Afinogen/get-mail#6] opened 2017-05-16 17:09 UTC
I get this error current() expects parameter 1 to be array, null given
It is only when I receive this type of mail.

Return-path: <info@xxxxxxx.co.za>
Received: from www400.jnb1.host-h.net ([196.22.142.87])
	by antispam3-jnb1.host-h.net with esmtpsa (TLSv1.2:DHE-RSA-AES128-SHA:128)
	(Exim 4.85)
	(envelope-from <info@xxxxxxx.co.za>)
	id 1b80FO-0005pM-Np
	for Septemberashley1@googlemail.com; Wed, 01 Jun 2016 09:07:29 +0200
Received: from getincvqjf by www400.jnb1.host-h.net with local (Exim 4.80)
	(envelope-from <info@xxxxxxx.co.za>)
	id 1b80FO-0006PK-6R
	for Septemberashley1@googlemail.com; Wed, 01 Jun 2016 09:07:22 +0200
To: Septemberashley1@googlemail.com
Subject: Congratulations for registering with xxxxxxx.co.za
X-PHP-Originating-Script: 1736:Message.php
From: "xxxxxxx" <info@xxxxxxx.co.za>
Reply-To: "Ashley" <Septemberashley1@googlemail.com>
X-Sender: info@xxxxxxx.co.za
X-Mailer: X-Mailer: werx
X-Priority: 3 (Normal)
Message-ID: <574e89aa2a8ec@xxxxxxx.co.za>
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary="B_ALT_574e89aa2a93b"
Date: Wed, 01 Jun 2016 09:07:22 +0200
X-Filter-ID: s0sct1PQhAABKnZB5plbIc/nJJTAJ+pm4act6O7cktGjT/LWuJWY0ikYTHC/EnAnx1wTMkEUUoeb
 KIhkyzl2dF816iRLYazEBLL01seSiR7GOC2k9Jbh0GDk/XRmXgLSHg/Xsvfe9iWdV3K9UVh7vFL3
 4KBO08fD2CHHpDrcuVdpYpSeNT797UD8dHTqZPSGBJYfmwoqUVZ+JoXoSa/1K1FfEoXm0/FPF8PR
 0w363lk4Xgr6kxG7pVOjqIEc6bQXeZGMARYx0l9ckgEjGO0PJGw8oRjljmbQIPnY50eAbrC5M1rs
 hWxsw1/gXTMtnmqhaVsmCjkZoM4PNfGdGztkpNzKfmoFMnQwh+RMs/ed5cp+ruoONuN8YJYvbnJV
 F5Vadj5qQk2EvmoC22/NQEvGRBMKadyTJzauXN/o8U8+Jw7tJQUR2RipwM5s25gqvdrL3jR5NeVa
 JQBh0uawl0Cg8sydXM/IHdDxHoubQaZx2FERK/tXdd/zQC4mB+/s7ue/QjCDM/SZTa7/uQHi3pye
 gNWCek+aT//254mQTsBpOhk+dvusjRV96oP1cmFb05OH8vQZQ/bWkyVtqT3h1YOVwv6Pnm0/GUWq
 RiM0QhIxEetoh9VoIekQHpwUfpYnEThm4w1g5kvKQeJjFcKGMW8EbEr48fpjx/1kzbywqt6D7+7q
 Ym0U74VVkBOOXFfs0Foe
X-Report-Abuse-To: spam@antispammaster.host-h.net
X-Originating-IP: 196.22.142.87
X-SpamExperts-Domain: xxxxxxx.co.za
X-SpamExperts-Username: 
Authentication-Results: host-h.net; auth=pass (login) smtp.auth=@xxxxxxx.co.za
X-SpamExperts-Outgoing-Class: unsure
X-SpamExperts-Outgoing-Evidence: Combined (0.37)
X-Recommended-Action: accept

This is a multi-part message in MIME format.
Your email application may not support this format.

--B_ALT_574e89aa2a93b
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Welcome to xxxxxxx!
 &nbsp;

**Comment by Afinogen** [comment] 2017-05-17 05:56
Do you use the latest version of the branch master?
I checked your example, the script returned the correct value
`multipart/alternative; boundary="B_ALT_574e89aa2a93b"`

But the body of the message did not appear. Is the format of the letter correct? Only with changed data?

**Comment by itecassist** [comment] 2017-05-17 06:20
Hi,

 

Yes, I’m using the latest version. I only get this error from a specific host, so I will assume that there is something wrong with it.

 

This is an amaizing package and really easy to work with. 

 

Thank you verymuch for all you effords.

 

Kind regards

 

Stuart Harrison

**Comment by Afinogen** [comment] 2017-05-17 06:29
Thanks for the feedback! I will not close the issue yet. Probably I will manage to catch an error

**Comment by itecassist** [comment] 2017-05-17 06:58
I can forward the email to you then you will have it if that would help.

**Comment by Afinogen** [comment] 2017-05-17 07:03
> I can forward the email to you then you will have it if that would help.

Well, pack to the archive. E-mail - afinogen89@gmail.com

**Comment by itecassist** [comment] 2017-05-24 11:34
I send you a mail with the error and the eml file

**Comment by Afinogen** [comment] 2017-05-24 11:46
Thanks, I understood what the problem is. Do you use the FIle or Pop3 class when an error occurs?

**Comment by itecassist** [comment] 2017-05-24 16:10
Hi,

 

Here is the code I use:

 

$folder = $_SERVER['DOCUMENT_ROOT'] . '/documents/'.$id.'/';

$storage = new \afinogen89\getmail\storage\File(['path' => $folder]);

$msg = $storage->getMessage(0);
$mail['from_email']=$msg->getHeaders()->getFrom();
$mail['from_name']=$msg->getHeaders()->getFromName();
$mail['to']=$msg->getHeaders()->getTo();
$mail['subject']=$msg->getHeaders()->getSubject();
$mail['date']=date('Y-m-d H:i:s', strtotime($msg->getHeaders()->getDate()));
$content=[];
foreach ($msg->getParts() as $part) {
    $content[$part->contentType]=$part->getContentDecode();
}

if(isset($content['text/html']))
{
    $mail['body']=$content['text/html'];
}else{
    $mail['body']=$content['text/plain'];
}

**Comment by Afinogen** [comment] 2017-05-25 19:36
A day ago I made corrections, now it works?

**Comment by kopyrin** [comment] 2017-07-03 09:20
В примере названия функции не такие как в сырцах. PHPShtorm ругается на них

**Comment by Afinogen** [comment] 2017-07-10 10:50
@kopyrin Исправил файл
П.С. Если ошибка не относится к issue лучше создать новый )

**Closed as completed** 2017-07-19 10:50 UTC
